version: "3"
services:
  stock:
    image: stock
    container_name: stock_service
    #build : 
    #context : . 
    #dockerfile : Dockerfile
    volumes: 
      - .:/STOCK
        #command: python3 manage.py runserver 0.0.0.0:8000
    command: gunicorn STOCK.wsgi:application --bind 0.0.0.0:8000
    expose : 
      - "8000"
  nginx:
    image: nginx
    container_name : nginx_service
    volumes: 
      - .:/STOCK
      - ./config/nginx:/etc/nginx/conf.d
#      - /home/docker/volumes/nginx:/etc/nginx/conf.d
#      - /home/docker/volumes/.static_root/:/static
    ports:
      - "80:80"
        #mysql:
          #image: mysql
    #environment:
            #MYSQL_ROOT_PASSWORD: "ds64079376*"
      #MYSQL_DATABASE: "STOCK"
      #MYSQL_USER: "e3hope"
      #MYSQL_PASSWORD: "ds64079376*"
      #volumes:
            #- .:/STOCK
        #- ./config/mysql:/mysql:rw
        #ports:
        #- "3305:3306"
    depends_on : 
    #- mysql
      - stock
