# Generated by Django 3.1.7 on 2021-06-06 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(blank=True, max_length=30, null=True)),
                ('mean', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'word',
                'managed': False,
            },
        ),
    ]
