# Generated by Django 3.1.7 on 2021-07-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_authgroup_authgrouppermissions_authpermission_authuser_authusergroups_authuseruserpermissions_board_'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockInvestment',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(blank=True, max_length=30, null=True)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('date_insert', models.DateTimeField(blank=True, null=True)),
                ('date_update', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mock_investment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserCapital',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=30)),
                ('capital', models.TextField(blank=True, null=True)),
                ('date_check', models.DateTimeField(blank=True, null=True)),
                ('date_insert', models.DateTimeField(blank=True, null=True)),
                ('date_update', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_capital',
                'managed': False,
            },
        ),
    ]
