# Generated by Django 3.1.7 on 2021-07-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_mockinvestment_usercapital'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookmarkGroup',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(blank=True, max_length=30, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('date_insert', models.DateTimeField(blank=True, null=True)),
                ('date_update', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bookmark_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BookmarkStock',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('group_idx', models.IntegerField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('date_insert', models.DateTimeField(blank=True, null=True)),
                ('date_update', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bookmark_stock',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Bookmark',
        ),
    ]
