# Generated by Django 3.1.7 on 2021-09-04 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20210713_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockOrder',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(blank=True, max_length=30, null=True)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('date_check', models.DateTimeField(blank=True, null=True)),
                ('date_insert', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mock_order',
                'managed': False,
            },
        ),
    ]
