# Generated by Django 3.1.7 on 2021-09-28 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_mockorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('company', models.CharField(blank=True, max_length=20, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('text', models.CharField(blank=True, max_length=1000, null=True)),
                ('date', models.CharField(blank=True, max_length=20, null=True)),
                ('img', models.CharField(blank=True, max_length=200, null=True)),
                ('href', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'news',
                'managed': False,
            },
        ),
    ]
