# Generated by Django 3.1.7 on 2021-11-16 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Krx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=1024, null=True)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=1024, null=True)),
                ('market', models.CharField(blank=True, max_length=1024, null=True)),
                ('dept', models.CharField(blank=True, max_length=1024, null=True)),
                ('close', models.FloatField(blank=True, db_column='Close', null=True)),
                ('changecode', models.IntegerField(blank=True, null=True)),
                ('changes', models.FloatField(blank=True, null=True)),
                ('chagesratio', models.FloatField(blank=True, null=True)),
                ('open', models.FloatField(blank=True, db_column='Open', null=True)),
                ('high', models.FloatField(blank=True, null=True)),
                ('low', models.FloatField(blank=True, null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('marcap', models.FloatField(blank=True, null=True)),
                ('stocks', models.FloatField(blank=True, null=True)),
                ('marketid', models.CharField(blank=True, max_length=1024, null=True)),
                ('rank', models.IntegerField(blank=True, db_column='Rank', null=True)),
                ('date', models.CharField(blank=True, db_column='Date', max_length=1024, null=True)),
            ],
            options={
                'db_table': 'krx',
                'managed': False,
            },
        ),
    ]
